# Generated by Django 3.2 on 2021-09-14 11:10

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('description', models.CharField(blank=True, max_length=320, null=True, verbose_name='项目描述')),
                ('start', models.DateField(blank=True, max_length=64, null=True, verbose_name='项目开始')),
                ('end', models.DateField(blank=True, max_length=64, null=True, verbose_name='项目结束')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': 'API项目管理',
            },
        ),
        migrations.CreateModel(
            name='RollingPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureName', models.CharField(max_length=32, verbose_name='图片名称')),
                ('path', models.FileField(upload_to='./static/crm/images/rollingPicture', verbose_name='图片路径')),
                ('description', models.TextField(max_length=320, verbose_name='图片描述')),
            ],
            options={
                'verbose_name_plural': '巨幕管理',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模板名称')),
                ('url', models.URLField(max_length=128, verbose_name='URL地址')),
                ('method', models.SmallIntegerField(choices=[(0, 'GET'), (1, 'POST'), (3, 'PUT'), (4, 'DELETE')], default=1, verbose_name='请求方式')),
                ('header', models.JSONField(default=api.models.default_header, null=True, verbose_name='header')),
                ('data', models.JSONField(help_text='\n    \n    <div class="alert border-0 border-start border-5 border-primary alert-dismissible fade show py-2">\n        <div class="d-flex align-items-center">\n            <div class="font-35 text-primary"><i class=\'bx bx-bookmark-heart\'></i>\n            </div>\n            <div class="ms-3">\n                <h6 class="mb-0 text-primary">提醒</h6>\n                <div>\n                ① 常规变量使用{{}}标识，例如：{{username}} <br>② 调用其他函数，则使用${function}|<>形式标识 <br>③ 需传参的函数，则使用${login}|<{{username}},{{password}}>标识 </span>\n                </div>\n            </div>\n        </div>\n        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>\n    </div>\n    \n    ', null=True, verbose_name='请求模板')),
                ('process_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='进程名称')),
                ('linux_order_str', models.CharField(blank=True, max_length=100, null=True, verbose_name='linux命令')),
                ('table_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='所需表名')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '请求接口模板',
            },
        ),
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='\n        <span style="color:gray;font-size:smaller;" class="glyphicon glyphicon-question-sign">填写PY测试文件名称，为字符串形式，建议首字母大写，例如：Login </span>\n    ', max_length=64, unique=True, verbose_name='Py文件名称')),
                ('class_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='测试类名称')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('project', models.ManyToManyField(help_text='<p class="text-dark small mt-1">Tips:hold down <kbd><kbd>ctrl</kbd></kbd>, to select more than one.</p>', to='api.ApiProject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name_plural': '用例集',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(help_text='\n        <span style="color:gray;font-size:smaller;" class="glyphicon glyphicon-question-sign">填写函数名称，建议全部小写，为字符串形式，例如：login_api </span>\n    ', max_length=64, unique=True, verbose_name='测试用例')),
                ('case_title', models.CharField(max_length=100, verbose_name='测试用例名称')),
                ('case_description', models.CharField(blank=True, max_length=320, null=True, verbose_name='测试用例描述')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('templates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.templates', verbose_name='模板')),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testsuit', verbose_name='用例集合')),
            ],
            options={
                'verbose_name_plural': '用例函数',
            },
        ),
        migrations.CreateModel(
            name='Sql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('sql', models.CharField(max_length=640, verbose_name='sql语句')),
                ('is_all', models.BooleanField(default=1, verbose_name='是否全量输出')),
                ('field_list', models.CharField(max_length=320, verbose_name='字段列表')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('case', models.ManyToManyField(help_text='<p class="text-dark small mt-1">Tips:hold down <kbd><kbd>ctrl</kbd></kbd>, to select more than one.</p>', to='api.TestCase', verbose_name='所涉用例')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(help_text='\n        <span style="color:gray;font-size:smaller;" class="glyphicon glyphicon-question-sign">填写测试场景名称，例如：用户名正确-密码错误 </span>\n    ', max_length=64, unique=True, verbose_name='场景名称')),
                ('parameter', models.JSONField(verbose_name='请求参数')),
                ('validator', models.JSONField(verbose_name='验证字段')),
                ('priority', models.SmallIntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], default=0, verbose_name='优先级')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testcase', verbose_name='测试函数（用例）')),
            ],
            options={
                'verbose_name_plural': '用例场景',
            },
        ),
    ]
