# Generated by Django 2.2.3 on 2021-06-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('description', models.CharField(blank=True, max_length=320, null=True, verbose_name='项目描述')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': 'API项目管理',
            },
        ),
        migrations.CreateModel(
            name='RollingPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureName', models.CharField(max_length=32, verbose_name='图片名称')),
                ('path', models.FileField(upload_to='./static/crm/images/rollingPicture', verbose_name='图片路径')),
                ('description', models.TextField(max_length=320, verbose_name='图片描述')),
            ],
            options={
                'verbose_name_plural': '巨幕管理',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模板名称')),
                ('url', models.URLField(max_length=128, verbose_name='URL地址')),
                ('method', models.SmallIntegerField(choices=[(0, 'GET'), (1, 'POST'), (3, 'PUT'), (4, 'DELETE')], default=1, verbose_name='请求方式')),
                ('header', models.CharField(default="{'Content-Type':'application/json'}", max_length=640, null=True, verbose_name='header')),
                ('data', models.TextField(help_text='\n    <div class="alert alert-danger alert-dismissible" role="alert">\n      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>\n      <strong>Warning!</strong> <br><span style="color:orange;font-size:smaller;">① 常规变量使用{{}}标识，例如：{{username}} <br>② 调用其他函数，则使用${function}|<>形式标识 <br>③ 需传参的函数，则使用${login}|<{{username}},{{password}}>标识 </span>\n    </div>\n    \n    ', max_length=2400, verbose_name='请求模板')),
                ('process_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='进程名称')),
                ('linux_order_str', models.CharField(blank=True, max_length=100, null=True, verbose_name='linux命令')),
                ('table_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='所需表名')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '请求接口模板',
            },
        ),
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='\n        <span style="color:gray;font-size:smaller;" class="glyphicon glyphicon-question-sign">填写PY测试文件名称，为字符串形式，建议首字母大写，例如：Login </span>\n    ', max_length=64, unique=True, verbose_name='Py文件名称')),
                ('class_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='测试类名称')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('project', models.ManyToManyField(to='api.ApiProject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name_plural': '用例集',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(help_text='\n        <span style="color:gray;font-size:smaller;" class="glyphicon glyphicon-question-sign">填写函数名称，建议全部小写，为字符串形式，例如：login_api </span>\n    ', max_length=64, unique=True, verbose_name='测试用例')),
                ('case_title', models.CharField(max_length=100, verbose_name='测试用例名称')),
                ('case_description', models.CharField(blank=True, max_length=320, null=True, verbose_name='测试用例描述')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('templates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Templates', verbose_name='模板')),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TestSuit', verbose_name='用例集合')),
            ],
            options={
                'verbose_name_plural': '用例函数',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(help_text='\n        <span style="color:gray;font-size:smaller;" class="glyphicon glyphicon-question-sign">填写测试场景名称，例如：用户名正确-密码错误 </span>\n    ', max_length=64, unique=True, verbose_name='场景名称')),
                ('parameter', models.TextField(max_length=2000, verbose_name='请求参数')),
                ('validator', models.CharField(default=200, max_length=100, verbose_name='验证字段')),
                ('priority', models.SmallIntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], default=0, verbose_name='优先级')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TestCase', verbose_name='测试函数（用例）')),
            ],
            options={
                'verbose_name_plural': '用例场景',
            },
        ),
    ]
