# Generated by Django 3.2.8 on 2021-12-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrecord',
            name='person',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='执行人员'),
        ),
        migrations.AlterField(
            model_name='executionrecord',
            name='create_date',
            field=models.DateField(default='2021-12-10', verbose_name='创建日期'),
        ),
    ]
