# Generated by Django 3.2.8 on 2021-11-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrecord',
            name='create_date',
            field=models.DateField(default='2021-11-18', verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='executionrecord',
            name='code',
            field=models.CharField(max_length=34, verbose_name='执行编码'),
        ),
    ]
