# Generated by Django 3.2 on 2021-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210713_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sql',
            name='case',
            field=models.ManyToManyField(help_text='<p class="text-dark small">Tips:hold down “Control”, or “Command” on a Mac, to select more than one.</p>', to='api.TestCase', verbose_name='所涉用例'),
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='project',
            field=models.ManyToManyField(help_text='<p class="text-dark small">Tips:hold down “Control”, or “Command” on a Mac, to select more than one.</p>', to='api.ApiProject', verbose_name='所属项目'),
        ),
    ]
