# Generated by Django 3.2 on 2021-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210901_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiproject',
            name='duration',
        ),
        migrations.AddField(
            model_name='apiproject',
            name='end',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='项目结束'),
        ),
        migrations.AddField(
            model_name='apiproject',
            name='start',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='项目开始'),
        ),
    ]
