# Generated by Django 3.2 on 2021-07-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210716_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproject',
            name='duration',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='项目周期'),
        ),
    ]
