# Generated by Django 3.2 on 2021-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210903_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproject',
            name='end',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='项目结束'),
        ),
        migrations.AlterField(
            model_name='apiproject',
            name='start',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='项目开始'),
        ),
    ]
