# Generated by Django 3.2 on 2021-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiproject_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sql',
            name='case',
            field=models.ManyToManyField(help_text='<p class="text-dark small mt-1">Tips:hold down <kbd><kbd>ctrl</kbd></kbd>, to select more than one.</p>', to='api.TestCase', verbose_name='所涉用例'),
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='project',
            field=models.ManyToManyField(help_text='<p class="text-dark small mt-1">Tips:hold down <kbd><kbd>ctrl</kbd></kbd>, to select more than one.</p>', to='api.ApiProject', verbose_name='所属项目'),
        ),
    ]
