# Generated by Django 3.2 on 2021-09-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210909_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='header',
            field=models.JSONField(default={'Content-Type': 'application/json'}, null=True, verbose_name='header'),
        ),
    ]
