# Generated by Django 3.2 on 2021-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_templates_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='header',
            field=models.JSONField(default=None, null=True, verbose_name='header'),
        ),
    ]
