# Generated by Django 3.2 on 2021-09-09 11:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_templates_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='header',
            field=models.JSONField(default=api.models.default_header, null=True, verbose_name='header'),
        ),
    ]
