'''全项目中英文字段对应，可用于生成结果对比文件，显示中文'''

projectFieldMapDict = {
    "stlmntSpdNm": "清算速度",
    "cntngncyIndctr": "应急标识",
    "flxblNetPrc": "弹性净价",
    "trdAcntCnShrtNm": "交易账户名称",
    "qtTp": "报价方式",
    "netPrc": "净价",
    "instnCd": "机构6位码",
    "nmnlVol": "券面总额",
    "ordrTpIndctr": "订单类型标识",
    "trdrCd": "交易员代码",
    "dir": "交易方向",
    "traTlCd": "债券代码",
    "bndsNm": "债券名称",
    "prdctCd": "产品代码",
    "stlmntDt": "结算日",
    "clrngMthd": "清算方式",
    "isrCd": "发行人代码",
    "qtSrc": "报价来源",
    "trdngAcntCd": "交易账户6位码",
    "srNoId": "产品序列号",
    "trdAcntSrNo": "交易账户序列号",
    "dlrSqncNoId": "交易员序列号",
    "instnSrno": "机构序列号",
    "ordrCd": "订单编号",
    "flxblSpd": "弹性价差",
    "dtCnfrm": "场次日期",
    "alctnIndctr": "分账标识",
    "yldToMrty": "到期收益率",
    "exrcsYld": "行权收益率",
    "bondTpNm": "债券类型名称",
    "ttm": "代偿期",
    "flxblExrcsYld": "弹性行权收益率",
    "flxblYldToMrty": "弹性到期收益率",
    "acrdIntrst": "应计利息",
    "prmrktBondF": "上市前债券标识"
}
