# Generated by Django 3.2 on 2021-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20210909_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steplog',
            name='detail',
            field=models.JSONField(null=True, verbose_name='操作详情'),
        ),
    ]
