# Generated by Django 3.2 on 2021-07-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16, verbose_name='操作用户')),
                ('action', models.CharField(max_length=8, verbose_name='操作类型')),
                ('model_name', models.CharField(max_length=32, verbose_name='涉及表信息')),
                ('detail', models.CharField(max_length=320, verbose_name='操作详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作日期')),
            ],
            options={
                'verbose_name_plural': '操作记录表',
            },
        ),
    ]
