# Generated by Django 3.2 on 2021-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_steplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='steplog',
            name='origin',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='原始数据'),
        ),
    ]
