# Generated by Django 3.2 on 2021-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_steplog_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steplog',
            name='action',
            field=models.CharField(max_length=8, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='steplog',
            name='detail',
            field=models.CharField(max_length=640, verbose_name='操作详情'),
        ),
        migrations.AlterField(
            model_name='steplog',
            name='model_name',
            field=models.CharField(max_length=32, verbose_name='表信息'),
        ),
        migrations.AlterField(
            model_name='steplog',
            name='origin',
            field=models.CharField(blank=True, max_length=640, null=True, verbose_name='原始数据'),
        ),
    ]
