# Generated by Django 3.2 on 2021-08-02 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20210723_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, help_text='\n    \n    <div class="alert alert-warning border-0 bg-info alert-dismissible fade show py-2">\n        <div class="d-flex align-items-center">\n            <div class="font-35 text-dark"><i class=\'bx bx-info-square\'></i>\n            </div>\n            <div class="ms-3">\n                <h6 class="mb-0 text-dark">Info Alerts</h6>\n                <div class="text-dark">管理员有所有表操作的权限，慎重勾选！</div>\n            </div>\n        </div>\n        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>\n    </div>\n    \n    ', verbose_name='超级用户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='\n                                <a href="../password/" class="btn btn-danger btn-sm" role="button">Reset Password</a>\n                                ', max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=320, verbose_name='代办内容')),
                ('statue', models.SmallIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
