# Generated by Django 3.2 on 2021-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20210802_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='task',
            field=models.DateTimeField(default='20:00', max_length=64, verbose_name='默认定时任务时间'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.CharField(max_length=32, verbose_name='代办内容'),
        ),
    ]
