# Generated by Django 3.2 on 2021-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20210802_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='test_integert',
            field=models.IntegerField(default=0, verbose_name='整数测试'),
        ),
    ]
