# Generated by Django 3.2.8 on 2021-11-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.PositiveSmallIntegerField(auto_created=True, max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='人员id')),
                ('name', models.CharField(max_length=32, verbose_name='人员姓名')),
                ('sex', models.SmallIntegerField(choices=[(1, '男性'), (0, '女性'), (2, '未知')], verbose_name='性别')),
                ('statue', models.SmallIntegerField(choices=[(1, '在职'), (0, '离职')], verbose_name='在职状态')),
                ('department', models.CharField(max_length=32, verbose_name='部门')),
                ('position', models.CharField(max_length=32, verbose_name='职务')),
                ('telephone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '人员信息',
            },
        ),
    ]
