# Generated by Django 3.2.8 on 2021-11-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoframe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
